---
title: "mockup"
author: "Kyuri Park"
date: "2023-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pracma)
library(dplyr)
library(magrittr)
library(ggplot2)
```


# Underlying mechanism
```{r}
fn1 <- function(t, y, p, ss) {
    a <- p[1]; b <- p[2]
    c <- p[3]; d <- p[4]
    e <- p[4]; f <- p[5]
    g <- p[6]; h <- p[7]
    dx <- a*y[1]*(1 - y[1]/3) * (b*y[3] - p[6]*ss)
    dy <- c*y[2]*(1 - y[2]/3) * d*y[1]
    dz <- e*y[3]*(1 - y[3]/3) * (f*y[2] - p[7]*ss)
    c(dx, dy, dz)
}

p0 <- c(0.3, 0.4, 0.44, 0.3, 0.2, 0.4, 0.53)
ic <- c(1.0, 1.0, 1.0)
ss <- 1 # social support

sol1 <- pracma::ode45(fn1, 0, 1000, ic, p = p0, ss = ss) |> 
  as.data.frame() |> 
  rename(insomnia = y.1, fatigue = y.2, feeldown = y.3)
# sol1$jittered <- apply(sol1$y, 2, function(x) x + rnorm(nrow(sol1$y), sd = 0.03))

sol1 |> tidyr::pivot_longer(!t, names_to = "symptom") |>
  ggplot(aes(x = t, y = value, group = symptom)) + 
  geom_line(aes(color=symptom)) + theme_minimal()

```


# Network estimation based on data
```{r}
library("psychonetrics")
library("qgraph")

layout(t(1:2))
chosen_var <- c("insomnia", "fatigue",   "feeldown")
res1 <- gvar(sol1, vars = chosen_var, estimator="FIML") %>% runmodel
# temporal network
temporal1 <- getmatrix(res1, "PDC") # PDC = Partial Directed Correlations
# layout 
L <- averageLayout(cor(sol1[-1]), temporal1)

# cross-sectioanl network
qgraph::qgraph(cor(sol1[-1]), theme = "colorblind", title = "GGM", labels = chosen_var, vsize = 12, layout= L)
# vector-autoregression 
qgraph(temporal1, theme = "colorblind", directed=TRUE, diag=TRUE,
title = "GVAR", vsize = 12, mar = rep(6,4),labels = chosen_var, layout = L)


```

